[package]
name = "shared-types"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = ["serde_json"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", optional = true }
